
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 13 23:05:30 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 8;
  public static final int TSTRING = 15;
  public static final int PCL = 3;
  public static final int POR = 35;
  public static final int CONCAT = 41;
  public static final int CASE = 19;
  public static final int CAP = 32;
  public static final int REPEAT = 18;
  public static final int REF = 40;
  public static final int NOT = 44;
  public static final int AND = 42;
  public static final int BAP = 5;
  public static final int IGUAL = 38;
  public static final int FUN = 20;
  public static final int TYPE = 21;
  public static final int OR = 43;
  public static final int INF = 30;
  public static final int TBOOL = 14;
  public static final int TDEC = 16;
  public static final int DIV = 36;
  public static final int IF = 17;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int TRUE = 27;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int MENOS = 34;
  public static final int MENOR = 47;
  public static final int NULL = 29;
  public static final int CCL = 4;
  public static final int MOD = 37;
  public static final int MENIG = 50;
  public static final int PCOMA = 7;
  public static final int MAYOR = 46;
  public static final int ENT = 24;
  public static final int VERT = 9;
  public static final int PAP = 31;
  public static final int BCL = 6;
  public static final int TINT = 13;
  public static final int ELSE = 10;
  public static final int PUNTO = 39;
  public static final int MAYIG = 49;
  public static final int IDEN = 23;
  public static final int THEN = 11;
  public static final int STRING = 26;
  public static final int DEC = 25;
  public static final int FALSE = 28;
  public static final int STRUCT = 12;
  public static final int ES_IGUAL = 48;
  public static final int DEREF = 45;
  public static final int MAS = 33;
}

