
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jun 15 23:47:33 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DOSPUNTOS = 8;
  public static final int TSTRING = 15;
  public static final int PCL = 3;
  public static final int POR = 36;
  public static final int CONCAT = 42;
  public static final int CASE = 20;
  public static final int CAP = 33;
  public static final int REPEAT = 19;
  public static final int REF = 41;
  public static final int NOT = 45;
  public static final int AND = 43;
  public static final int BAP = 5;
  public static final int IGUAL = 39;
  public static final int FUN = 21;
  public static final int TYPE = 22;
  public static final int OR = 44;
  public static final int INF = 31;
  public static final int TBOOL = 14;
  public static final int TDEC = 16;
  public static final int DIV = 37;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int RETURN = 23;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int MENOS = 35;
  public static final int MENOR = 48;
  public static final int NULL = 30;
  public static final int CCL = 4;
  public static final int MOD = 38;
  public static final int TNULL = 17;
  public static final int MENIG = 51;
  public static final int PCOMA = 7;
  public static final int MAYOR = 47;
  public static final int ENT = 25;
  public static final int VERT = 9;
  public static final int PAP = 32;
  public static final int BCL = 6;
  public static final int TINT = 13;
  public static final int ELSE = 10;
  public static final int PUNTO = 40;
  public static final int MAYIG = 50;
  public static final int IDEN = 24;
  public static final int THEN = 11;
  public static final int STRING = 27;
  public static final int DEC = 26;
  public static final int FALSE = 29;
  public static final int STRUCT = 12;
  public static final int ES_IGUAL = 49;
  public static final int DEREF = 46;
  public static final int MAS = 34;
}

